baseurl:
timezone: Europe/Berlin
permalink: /:categories/:year/:month/:day/:title.html
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
highlighter: rouge
excerpt_separator:

exclude: ["old", "psd", "caogao", "*.txt", "*.bat", "*.zip", "*.rar"]
